// This file is automatically generated. Do not edit it directly.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Credentials not found. Returning a fallback dummy client to prevent startup crashes.",
    );
    // Return a safe proxy that no-ops and returns graceful defaults
    const dummyClient = new Proxy({} as any, {
      get(target, prop) {
        if (prop === "auth") {
          return new Proxy({} as any, {
            get(t, p) {
              if (p === "getSession" || p === "getUser") {
                return () => Promise.resolve({ data: { session: null, user: null }, error: null });
              }
              if (p === "onAuthStateChange") {
                return () => ({ data: { subscription: { unsubscribe: () => {} } } });
              }
              return () => Promise.resolve({ data: {}, error: null });
            },
          });
        }

        // Handle common inspect/bundler/framework property accesses
        if (
          prop === "then" ||
          prop === "constructor" ||
          prop === "toJSON" ||
          typeof prop === "symbol" ||
          String(prop).startsWith("__")
        ) {
          return undefined;
        }

        const chainable = () => ({
          select: chainable,
          insert: chainable,
          update: chainable,
          delete: chainable,
          eq: chainable,
          single: chainable,
          maybeSingle: chainable,
          order: chainable,
          limit: chainable,
          then: (resolve: any) =>
            resolve({ data: null, error: new Error("Supabase is not configured") }),
        });

        return chainable;
      },
    });
    return dummyClient;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
